# Generated by Django 5.2.17 on 2026-08-14 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('owner', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=512, unique=True)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('committed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='ACIApp.repository')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField()),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=255)),
                ('source_branch', models.CharField(max_length=255)),
                ('target_branch', models.CharField(max_length=255)),
                ('base_sha', models.CharField(max_length=40)),
                ('head_sha', models.CharField(max_length=40)),
                ('state', models.CharField(default='open', max_length=20)),
                ('is_merged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='ACIApp.repository')),
            ],
            options={
                'indexes': [models.Index(fields=['repository', 'state'], name='ACIApp_pull_reposit_0ae0c7_idx'), models.Index(fields=['head_sha'], name='ACIApp_pull_head_sh_504a6f_idx')],
                'constraints': [models.UniqueConstraint(fields=('repository', 'number'), name='unique_repository_pull_request')],
            },
        ),
    ]
