# Generated by Django 5.2.17 on 2026-08-17 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACIApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1024)),
                ('status', models.CharField(max_length=50)),
                ('additions', models.PositiveIntegerField(default=0)),
                ('deletions', models.PositiveIntegerField(default=0)),
                ('changes', models.PositiveIntegerField(default=0)),
                ('patch', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changed_files', to='ACIApp.commit')),
            ],
        ),
    ]
