# Generated by Django 5.2.17 on 2026-08-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACIApp', '0002_changedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='ACIApp.pullrequest'),
        ),
    ]
