# Generated by Django 5.2.17 on 2026-08-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACIApp', '0003_commit_pull_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('jira', 'Jira'), ('linear', 'Linear'), ('github', 'GitHub'), ('manual', 'Manual')], default='jira', max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='ACIApp.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('code', 'Code'), ('test', 'Test'), ('ci', 'CI'), ('runtime', 'Runtime')], max_length=30)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('stale', 'Stale'), ('invalid', 'Invalid')], default='valid', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('changed_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ACIApp.changedfile')),
                ('commit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ACIApp.commit')),
                ('pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ACIApp.pullrequest')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ACIApp.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_links', to='ACIApp.pullrequest')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_request_links', to='ACIApp.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('partial', 'Partial'), ('unverified', 'Unverified'), ('stale', 'Stale'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pull_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='ACIApp.pullrequest')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='ACIApp.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_links', to='ACIApp.evidence')),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='ACIApp.verification')),
            ],
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('repository', 'source', 'external_id'), name='unique_requirement_source_external_id'),
        ),
        migrations.AddConstraint(
            model_name='requirementpullrequest',
            constraint=models.UniqueConstraint(fields=('requirement', 'pull_request'), name='unique_requirement_pull_request'),
        ),
        migrations.AddConstraint(
            model_name='verificationevidence',
            constraint=models.UniqueConstraint(fields=('verification', 'evidence'), name='unique_verification_evidence'),
        ),
    ]
