# Generated by Django 5.2.17 on 2026-08-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACIApp', '0004_requirement_evidence_requirementpullrequest_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.UniqueConstraint(fields=('requirement', 'pull_request'), name='unique_requirement_pull_request_verification'),
        ),
    ]
