# Generated by Django 5.2.17 on 2026-08-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACIApp", "0005_verification_unique_requirement_pull_request_verification"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceInvalidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("invalidated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invalidations",
                        to="ACIApp.evidence",
                    ),
                ),
                (
                    "triggering_changed_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_invalidations",
                        to="ACIApp.changedfile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="evidenceinvalidation",
            constraint=models.UniqueConstraint(
                fields=("evidence", "triggering_changed_file"),
                name="unique_evidence_invalidation_trigger",
            ),
        ),
    ]
