# Generated by Django 5.2.17 on 2026-08-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACIApp', '0007_verificationrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('behavior', 'Behavior'), ('implementation', 'Implementation'), ('test', 'Test'), ('integration', 'Integration'), ('data', 'Data'), ('security', 'Security'), ('configuration', 'Configuration')], default='behavior', max_length=30)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expectations', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='ACIApp.requirement')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CriterionVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('satisfied', 'Satisfied'), ('partial', 'Partial'), ('missing', 'Missing'), ('not_applicable', 'Not Applicable'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='ACIApp.verification')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_results', to='ACIApp.requirementcriterion')),
            ],
            options={
                'ordering': ['evaluated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CriterionVerificationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('criterion_verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='ACIApp.criterionverification')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_verification_links', to='ACIApp.evidence')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('criterion_verification', 'evidence'), name='unique_criterion_verification_evidence')],
            },
        ),
        migrations.AddIndex(
            model_name='requirementcriterion',
            index=models.Index(fields=['requirement', 'is_active', 'order'], name='ACIApp_requ_require_4a58fa_idx'),
        ),
        migrations.AddIndex(
            model_name='criterionverification',
            index=models.Index(fields=['verification', 'criterion'], name='ACIApp_crit_verific_31a8b2_idx'),
        ),
    ]
