# Generated by Django 5.2.17 on 2026-08-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACIApp', '0008_requirementcriterion_criterionverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('unverified', 'Unverified'), ('stale', 'Stale'), ('failed', 'Failed')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rationale', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='ACIApp.verification')),
            ],
            options={
                'indexes': [models.Index(fields=['verification', 'status'], name='ACIApp_deli_verific_054f76_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('verification',), name='unique_current_delivery_decision')],
            },
        ),
    ]
