# Generated by Django 5.2.17 on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACIApp", "0009_deliverydecision"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed Out"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("stdout", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                (
                    "duration_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_executions",
                        to="ACIApp.commit",
                    ),
                ),
                (
                    "verification_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_executions",
                        to="ACIApp.verificationrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["verification_run", "status"],
                        name="ACIApp_test_verific_45127f_idx",
                    ),
                    models.Index(
                        fields=["commit", "status"],
                        name="ACIApp_test_commit__630d15_idx",
                    ),
                ],
            },
        ),
    ]
