# Generated by Django 5.2.17 on 2026-08-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ACIApp", "0010_testexecution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="aci_repositories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]